### PR TITLE
Invocable arguments

### PR DESCRIPTION
**Pull request by Blinke**
Thank you for your contribution!
Before submitting this PR, please make sure:

- [ ] If you are fixing something **other than a typo**, **please always create an issue first**. 
      Otherwise, your PR will probably be rejected
- [ ] Your addition is not too large. The more files/lOC changed means the longer it'll take to be addressed by me (the maintainer)
- [ ] Your code builds clean without any errors or warnings
- [ ] You have added user documentation for any additional features
- [ ] You have added unit tests which (a) pass and (b) sufficiently cover your changes

Other Notes:

Coravel is created with a specific vision and philosophy:

- Simple, fluent and straightforward public APIs
- Easy to read documentation that guides users coherently
- Building **useful** features because they really are useful - not just for the sake of adding "more features"

To that effect, don't feel bad when many changes are asked of your PR 😉

### CODE REVIEW

**Comment by Blinke** [comment]
Proposed solution for #128

**Comment by jamesmh** [comment]
Thanks for this! I've been away for a bit - hoping to get around to checking this out soon 😊

**Comment by jamesmh** [comment]
I left a comment on the main issue around approaching this feature a bit differently: https://github.com/jamesmh/coravel/issues/128#issuecomment-569972476

Are you willing to tackle that change?

**Comment by jamesmh** [comment]
In this case, I'm thinking something like:

```c#
 IScheduleInterval ScheduleWithParams<T>(Action<T> setParameters) where T : IInvocable;
```

Does that make sense?

BTW awesome PR 👍 

Didn't know you could use` ActivatorUtilities.CreateInstance` while accepting the service provider too 👌

**Comment by jamesmh** [comment]
Just hold on if you are planning on tackling this. Going to wait to see how the discussion on the issue goes.

**Comment by Blinke** [comment]
Glad you liked the PR! I'd definitely be up for implementing any changes that get brought up in the discussions.

**Comment by jamesmh** [comment]
Great! I'll comment here once there's a solid direction 👌

**Comment by jamesmh** [comment]
So not much of a discussion on the issue 😅

Whenever you want, you can go ahead and make the changes we talked about using an `Action<T>` to set any properties on an invocable when scheduling it. 

Thanks again!

**Comment by Blinke** [comment]
I had a quick look at it and came across something I hadn't considered. I figured I'd do something like this to follow the same pattern as the other methods in `ScheduledEvent`:

    public static ScheduledEvent WithInvocableAndParams<T>(IServiceScopeFactory scopeFactory, Action<T> propertyInjectorAction) where T : IInvocable
    {
        var scheduledEvent = WithInvocableType(scopeFactory, typeof(T));
        scheduledEvent._propertyInjectorAction = propertyInjectorAction;
        return scheduledEvent;
     }

The problem is that we can't conveniently store the `Action<T>` in the `ScheduledEvent` class due to it not being generic. We also can't apply the the `Action<T>` once we resolve the invocable from the service provider since it's just an `IInvocable` at that point and not of type `T`.

A possible solution would be making a `ScheduledEvent<T>` class to solve the above. It might need to exist alongside the original class to support calling `ScheduledEvent WithInvocableType(IServiceScopeFactory scopeFactory, Type invocableType)` directly. That seems like a pretty big change for a small benefit to me.

Any thoughts? 🙂

**Comment by jamesmh** [comment]
I think we'll stick with the original idea that you've already coded 👍

On the right-hand side of this PR screen, there should be a checkbox to allow edits from maintainers. Could you check that?

Then I can add some documentation to the PR and we'll be set to merge 😊

**Comment by Blinke** [comment]
Checkbox should be checked now!

**Comment by jamesmh** [comment]
Great job - thanks!

**Comment by schmitch** [comment]
@jamesmh does this also work with database scheduling and the dashboard (coravel pro)?

**Comment by jamesmh** [comment]
Not yet, but it is something a few people have mentioned in the past. You could create an issue: https://github.com/jamesmh/coravelpro/issues

**Pull request merged**
